CMD >  sqlplus /nolog
 SQL conn /as sysdba
 
 ALTER SESSION SET "_ORACLE_SCRIPT"=true;
 CREATE USER SPRING IDENTIFIED BY 1234;
 GRANT CONNECT, RESOURCE TO SPRING;
 ALTER USER SPRING DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

----------------------------------

CREATE  TABLE MENUS (
    MENU_ID     VARCHAR2(6)   PRIMARY KEY   -- 매뉴아이디
  , MENU_NAME   VARCHAR2(30)     -- 메뉴이름
  , MENU_SEQ    NUMBER(6)        -- 순번
)

INSERT  INTO   MENUS  VALUES ( 'MENU01', 'HTML',       1);
INSERT  INTO   MENUS  VALUES ( 'MENU02', 'CSS',         2);
INSERT  INTO   MENUS  VALUES ( 'MENU03', 'JAVASCRIPT',  3);
COMMIT;

SELECT * FROM MENUS;
---------------------------
--멀티 게시판
DROP    TABLE  BOARD;
CREATE  TABLE  BOARD (
     IDX          NUMBER(8, 0)         PRIMARY KEY
   , MENU_ID      VARCHAR2(6)
      REFERENCES  MENUS ( MENU_ID )
   , TITLE        VARCHAR2(300 BYTE)   NOT NULL
   , CONTENT      VARCHAR2(4000 BYTE)
   , WRITER       VARCHAR2(12)
   , REGDATE      DATE                 DEFAULT  SYSDATE
   , HIT          NUMBER(9, 0)         DEFAULT  0
);

INSERT INTO BOARD (IDX, MENU_ID, TITLE, CONTENT, WRITER)
 VALUES (
   ( SELECT NVL(MAX(IDX),0)+1 FROM BOARD  )
   , 'MENU01', '반갑습니다', '인사드립니다', 'ADMIN');
COMMIT;  